[package]
name = "terminal-serial"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [[bin]]
# name = "terminal-serial"
# path = "src/main.rs"

[dependencies]
clap = {version = "2.27.1", features = ["yaml"]}
winreg = "0.10.1"
serial = "0.4.0"
libc = "0.2.124"